commonLabels:
  app.kubernetes.io/genereted-by: JHipster

namespace: argo_hello_world

resources:
  - namespace.yml
  # Individual apps
  - argo_test-k8s/argo_test-deployment.yml
  - argo_test-k8s/argo_test-service.yml
  - argo_test-k8s/argo_test-postgresql.yml
  - argo_test-k8s/jwt-secret.yml
  # messagebroker
  - messagebroker-k8s/kafka.yml
# service discovery eureka/consul

patchesJson6902:
