apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: arg_hello_world/argo_test
      context: ../argo_hello_world
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
