apiVersion: v1
kind: Secret
metadata:
  name: argo_test-postgresql
  namespace: argo_hello_world
  labels:
    app: argo_test-postgresql
type: Opaque
data:
  postgresql-password: YjFiMmE2ODEzYWI3Mjk4ZGEyYzVhZDYzOTFmMTYxNjk1YjAwMmVmN2QxODBmMzZmY2FjZjRkMjA0M2Y3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo_test-postgresql
  namespace: argo_hello_world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo_test-postgresql
  template:
    metadata:
      labels:
        app: argo_test-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.3
          env:
            - name: POSTGRES_USER
              value: argo_test
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argo_test-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: argo_test-postgresql
  namespace: argo_hello_world
spec:
  selector:
    app: argo_test-postgresql
  ports:
    - port: 5432
