apiVersion: v1
kind: Service
metadata:
  name: argo_test
  namespace: argo_hello_world
  labels:
    app: argo_test
spec:
  selector:
    app: argo_test
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
