apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: argo_hello_world
type: Opaque
data:
  secret: Tm1aak1HRmxOMlpsTkRjMVl6RmhabU14TlRjNE0yUTBaRGhqWkRVeVkyRTRPVGRrTmpnNE1XTXlOV1UyWXpRek16RXlaRGRtWVdRMFlURmpaVEEzWW1ObVpUQTROR1JpTmpZMk16UTNPVEV5WWpSaE16QTVZMkpqWkRnMlpHUXlNREJrTkRRNU5tVTBaV0V4TVRnME1UVXlNVEV5Tm1Nd1l6RmtaV0ZqTWpVPQ==
